version: "3.8"

services:
  # Database
  db:
    image: mysql:latest

    expose:
      - 3306
    
    volumes:
      - ./db_vol:/var/lib/mysql
  
    restart: always

    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=planPal

    networks:
      - planpal

  # Backend
  planpal-backend:
    image: docker.io/sherifemad21/planpal:backend

    build:
      context: ./Backend
      dockerfile: Dockerfile

    environment:
      - DB_ADDRESS=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - ML_ADDRESS=bertNlt
      - ML_PORT=5000

    restart: always

    depends_on:
      - db
      - bertNlt

    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://db:3306 && curl -f http://bertNlt:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 15s

    networks:
      - planpal

  # Frontend
  planpal_frontend:
    image: docker.io/sherifemad21/planpal:frontend

    build:
      context: ./Frontend
      dockerfile: Dockerfile

    environment:
      - BACKEND_BASE_URL=http://planpal-backend:8080

    ports:
      - "3000:80"

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://planpal-backend:8080/api/v1/venue/getAllVenues || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 15s

    depends_on:
      - planpal-backend

    networks:
      - planpal

  # ML model
  bertNlt:
    image: docker.io/sherifemad21/planpal:rating-service

    build:
      context: ./RatingService
      dockerfile: Dockerfile

    restart: always
    
    ports:
      - "5000:5000"

    environment:
      - BACKEND_ADDRESS=http://planpal-backend:8080 # Use the service name as the address

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://planpal-backend:8080/api/v1/venue/getAllVenues || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 15s


    networks:
      - planpal

networks:
  planpal:
